# Generated by Django 4.2.5 on 2023-12-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temphapis', '0003_alter_userhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
